apiVersion: v1
kind: Service

#pod label and service label should be same
metadata:
  name: hello-svc
  labels:
    app: myapp

spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
  selector:
    app: myapp
   

